version: '2'

services:
  postgres:
    image: postgres:9.5-alpine
    ports:
      - 5433:5432
    expose:
      - 5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql
      - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    links:
      - postgres
    volumes:
      - .:/django
    entrypoint:
      - /run-django.sh
    ports:
      - 8000:8000
