---
#- name: pull latest code from git
#  when: git_pull is defined and git_pull
#  git: repo={{ git_repo }}
#       version={{ git_branch }}
#       dest={{ project_dir }}
#       accept_hostkey=yes
#  tags: git_pull

- name: sync project code from local dir
  synchronize:
    src: '{{ local_project_dir }}'
    dest: '{{ project_dir }}'
    recursive: yes
    delete: yes
    verify_host: yes
    rsync_opts:
      - "--exclude=*.pyc"
      - "--exclude=__pycache__*"
      - "--exclude=ansible*"
      - "--exclude=docker*"
      - "--exclude=media*"
  tags: django

- name: clear .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: '{{ project_dir }}'
  changed_when: False
  tags: django
