---
gunicorn_user: gunicorn
gunicorn_group: gunicorn
gunicorn_num_workers: 3  # (2x num CPUs) + 1
gunicorn_max_requests: 0

dependencies:
  - '@Development Tools'
  - python35u
  - python35u-devel
  - python35u-pip
  - supervisor
  - git

supervisor_svc: supervisord
supervisor_dir: /etc/supervisord.d
supervisor_ext: ini

python: python3.5
pip: pip3.5

python_path: '/usr/bin/{{ python }}'
virtualenv_dir: '/virtualenvs/{{ app_name }}_env'
project_dir: '{{ virtualenv_dir }}/{{ project_name }}'
requirements_path: '{{ project_dir }}/requirements.txt'

django_environment:
  DJANGO_SETTINGS_MODULE: '{{ django_settings_module }}'
  DJANGO_SECRET_KEY: '{{ django_secret_key }}'
  DJANGO_DEBUG: '{{ django_debug }}'
  DJANGO_DATABASE_NAME: '{{ django_database_name }}'
  DJANGO_DATABASE_USER: '{{ django_database_user }}'
  DJANGO_DATABASE_PASSWORD: '{{ django_database_password }}'
  DJANGO_DATABASE_HOST: '{{ django_database_host }}'
  DJANGO_DATABASE_PORT: '{{ django_database_port }}'
  DJANGO_ALLOWED_HOSTS: '{{ django_allowed_hosts }}'
  DJANGO_STATIC_ROOT: '{{ django_static_root }}'
  DJANGO_MEDIA_ROOT: '{{ django_media_root }}'
  DJANGO_USE_X_FORWARDED_HOST: '{{ django_use_x_forwarded_host }}'
  DJANGO_TIMEZONE: '{{ django_timezone }}'

application_log_dir: '/var/log/{{ app_name }}'
gunicorn_log_file: '{{ application_log_dir }}/gunicorn_supervisor.log'
gunicorn_run_dir: /var/run/gunicorn
gunicorn_socket_path: '{{ gunicorn_run_dir }}/gunicorn.sock'
nginx_access_log_file: '{{ application_log_dir }}/nginx_access.log'
nginx_error_log_file: '{{ application_log_dir }}/nginx_error.log'

run_django_syncdb: no
run_django_db_migrations: yes
run_django_fixtures: no
run_django_collectstatic: yes
